modify

diff --git a/.github/workflows/cd-infrastructure-deployment.yaml b/.github/workflows/cd-infrastructure-deployment.yaml
--- a/.github/workflows/cd-infrastructure-deployment.yaml
+++ b/.github/workflows/cd-infrastructure-deployment.yaml
@@ -174,7 +174,7 @@ jobs:
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3  
         with:
-          terraform_version: "v1.6"
+          terraform_version: "v1.12.2"
 
       - name: Enable Terraform Git actions to use Github Apps Token
         uses: de-vri-es/setup-git-credentials@v2.0.9
@@ -205,42 +205,65 @@ jobs:
       - name: Terraform Plan for ${{ matrix.subdomain }}
         working-directory: ${{ matrix.path }}
         run: |
+          set +e
           terraform plan \
             -out=plan-${{ matrix.subdomain }}.tfplan \
             -input=false \
-            -var-file=${{ github.event.inputs.env }}/${{ github.event.inputs.env }}.tfvars
+            -var-file=${{ github.event.inputs.env }}/${{ github.event.inputs.env }}.tfvars \
+            -no-color \
+            -detailed-exitcode
+          
+          exit_code=$?
+          echo "Terraform exit code: $exit_code"
 
-          terraform show -no-color plan-${{ matrix.subdomain }}.tfplan |
-          awk '
-            /^  # / {
-              line=$0
-              sub(/^  # /,"",line)                        # strip leading "  # "
-              addr=line
-              sub(/ (will be|must be) .*/,"",addr)        # remove trailing " will be ..." / " must be ..."
-              act="other"
-              if (line ~ /will be created/)              act="create";
-              else if (line ~ /will be destroyed/)       act="destroy";
-              else if (line ~ /will be updated in-place/)act="update";
-              else if (line ~ /(must be|will be) replaced/) act="replace";
+          if [ "$exit_code" -eq 0 ]; then
+            echo "No changes."
+          elif [ "$exit_code" -eq 2 ]; then
+            echo "Changes detected."
+          else
+            echo "Terraform plan failed."
+            exit 1
+          fi
 
-              # Short address: strip module prefixes like module.foo. or module.bar[0].
-              short=addr
-              gsub(/(^|\.)module\.[^.]+(\[[0-9]+\])?(\.|$)/,".",short)
-              gsub(/\.\./,".",short); sub(/^\./,"",short); sub(/\.$/,"",short)
 
-              printf "%s\t%s\t%s\n", act, addr, short
-            }
-          ' |
-          while IFS=$'\t' read -r act addr short; do
-            case "$act" in
-              create)  echo "### ✅ \`$short\` *(full: \`$addr\`)* will be **created**"   >> "$GITHUB_STEP_SUMMARY" ;;
-              update)  echo "### 🔁 \`$short\` *(full: \`$addr\`)* will be **updated**"   >> "$GITHUB_STEP_SUMMARY" ;;
-              destroy) echo "### ❌ \`$short\` *(full: \`$addr\`)* will be **destroyed**" >> "$GITHUB_STEP_SUMMARY" ;;
-              replace) echo "### ♻️  \`$short\` *(full: \`$addr\`)* will be **replaced**" >> "$GITHUB_STEP_SUMMARY" ;;
-              *)       echo "### ℹ️  \`$short\` *(full: \`$addr\`)* action: $act"         >> "$GITHUB_STEP_SUMMARY" ;;
-            esac
-          done
-          terraform show -no-color plan-${{ matrix.subdomain }}.tfplan | grep '^Plan:' >> $GITHUB_STEP_SUMMARY
+
+
+          # terraform plan \
+          #   -out=plan-${{ matrix.subdomain }}.tfplan \
+          #   -input=false \
+          #   -var-file=${{ github.event.inputs.env }}/${{ github.event.inputs.env }}.tfvars
+
+          # terraform show -no-color plan-${{ matrix.subdomain }}.tfplan |
+          # awk '
+          #   /^  # / {
+          #     line=$0
+          #     sub(/^  # /,"",line)                        # strip leading "  # "
+          #     addr=line
+          #     sub(/ (will be|must be) .*/,"",addr)        # remove trailing " will be ..." / " must be ..."
+          #     act="other"
+          #     if (line ~ /will be created/)              act="create";
+          #     else if (line ~ /will be destroyed/)       act="destroy";
+          #     else if (line ~ /will be updated in-place/)act="update";
+          #     else if (line ~ /(must be|will be) replaced/) act="replace";
+
+          #     # Short address: strip module prefixes like module.foo. or module.bar[0].
+          #     short=addr
+          #     gsub(/(^|\.)module\.[^.]+(\[[0-9]+\])?(\.|$)/,".",short)
+          #     gsub(/\.\./,".",short); sub(/^\./,"",short); sub(/\.$/,"",short)
+
+          #     printf "%s\t%s\t%s\n", act, addr, short
+          #   }
+          # ' |
+          # while IFS=$'\t' read -r act addr short; do
+          #   case "$act" in
+          #     create)  echo "### ✅ \`$short\` *(full: \`$addr\`)* will be **created**"   >> "$GITHUB_STEP_SUMMARY" ;;
+          #     update)  echo "### 🔁 \`$short\` *(full: \`$addr\`)* will be **updated**"   >> "$GITHUB_STEP_SUMMARY" ;;
+          #     destroy) echo "### ❌ \`$short\` *(full: \`$addr\`)* will be **destroyed**" >> "$GITHUB_STEP_SUMMARY" ;;
+          #     replace) echo "### ♻️  \`$short\` *(full: \`$addr\`)* will be **replaced**" >> "$GITHUB_STEP_SUMMARY" ;;
+          #     *)       echo "### ℹ️  \`$short\` *(full: \`$addr\`)* action: $act"         >> "$GITHUB_STEP_SUMMARY" ;;
+          #   esac
+          # done
+          # terraform show -no-color plan-${{ matrix.subdomain }}.tfplan | grep '^Plan:' >> $GITHUB_STEP_SUMMARY
 
       - name: Upload Plan Output for ${{ matrix.subdomain }}
         uses: actions/upload-artifact@v4
